[package]
name = "App"
version = "0.1.0"
authors = ["Insert Name Here <legendofmiracles@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
clap = "2.33.0"